spring.application.name=auth-service

# ========== DATABASE (DISABLED FOR DEPLOYMENT) ==========
spring.datasource.url=jdbc:mysql://localhost:3306/auth_service
 spring.datasource.username=root
 spring.datasource.password=varunga4825V
 spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

 spring.jpa.hibernate.ddl-auto=update
 spring.jpa.show-sql=true
 spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# ========== JWT ==========
jwt.secret=MySuperSecretKeyForJwtDontShareveryconfidental
jwt.expiration=3600000

# ========== PORT (VERY IMPORTANT) ==========
#server.port=${PORT:8080}
server.port=8080